const quotes = [
    "Programming is the closest thing we have to magic.",
    "Code is like humor. When you have to explain it, it’s bad.",
    "To iterate is human, to recurse divine.",
    "The best error message is the one that never shows up.",
    "A good programmer is someone who always looks both ways before crossing a one-way street.",
    "Java is to JavaScript what car is to carpet.",
    "If the code and the comments disagree, the comments are probably wrong.",
    "There are only two hard things in computer science: cache invalidation and naming things.",
    "It’s not a bug – it’s an undocumented feature.",
    "Software is a great combination between artistry and engineering.",
    "The only valid measurement of code quality: WTFs/minute.",
    "The best thing about a boolean is even if you are wrong, you are only off by a bit.",
    "The root of all evil is premature optimization.",
    "First, solve the problem. Then, write the code.",
    "Programming is thinking, not typing.",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to build bigger and better idiots. So far, the universe is winning.",
    "Don’t comment bad code—rewrite it.",
    "The most important property of a program is whether it accomplishes the intention of its user.",
    "Without requirements or design, programming is the art of adding bugs to an empty text file.",
    "It’s harder to read code than to write it.",
    "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.",
    "The only code that is easy to maintain is the code that doesn’t exist.",
    "Good code is its own best documentation.",
    "In software, the sky is the limit. There are always new challenges, and there is always something new to learn.",
    "Any code of your own that you haven’t looked at for six or more months might as well have been written by someone else.",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.",
    "Deleted code is debugged code.",
    "It’s not that I’m so smart, it’s just that I stay with problems longer.",
    "Make it work, make it right, make it fast.",
    "If you think your users are idiots, only idiots will use it.",
    "The function of good software is to make the complex appear to be simple.",
    "The best software is reliable, understandable, and scalable.",
    "Programming is not about typing, it’s about thinking.",
    "There is no programming language–no matter how structured–that will prevent programmers from making bad programs.",
    "No one in the brief history of computing has ever written a piece of perfect software. It’s unlikely that you’ll be the first.",
    "Programming can be fun, so can cryptography; however, they should not be combined.",
    "It’s not just what it looks like and feels like. Design is how it works.",
    "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.",
    "The best error message is the one that never shows up.",
    "It’s not a bug – it’s an undocumented feature.",
    "Walking on water and developing software from a specification are easy if both are frozen.",
    "If debugging is the process of removing software bugs, then programming must be the process of putting them in.",
    "The only way to do great work is to love what you do.",
    "Code is like humor. When you have to explain it, it’s bad.",
    "A user interface is like a joke. If you have to explain it, it’s not that good.",
    "I think it’s very important to get more women into computing. My slogan is: Computing is too important to be left to men.",
    "I’m not a great programmer; I’m just a good programmer with great habits.",
    "Simplicity is the soul of efficiency.",
    "The computer was born to solve problems that did not exist before.",
    "Before software can be reusable it first has to be usable.",
    "Make it correct, make it clear, make it concise, make it fast. In that order.",
    "Programming is the art of telling another human what one wants the computer to do.",
    "The three great virtues of a programmer: laziness, impatience, and hubris.",
    "I’m not a great programmer; I’m just a programmer who writes great code.",
    "A language that doesn’t affect the way you think about programming is not worth knowing.",
    "The most damaging phrase in the language is: It’s always been done that way.",
    "Programmers are not to be measured by their ingenuity and their logic but by the completeness of their case analysis.",
    "The best programmers are not marginally better than merely good ones. They are an order-of-magnitude better, measured by whatever standard: conceptual creativity, speed, ingenuity of design, or problem-solving ability.",
    "The use of COBOL cripples the mind; its teaching should, therefore, be regarded as a criminal offense.",
    "If you can imagine a society in which the computer-robot is the only menial, you can imagine anything.",
    "A programming language is low level when its programs require attention to the irrelevant.",
    "In computing, turning the obvious into the useful is a living definition of the word ‘frustration’.",
    "Never memorize what you can look up in books.",
    "It’s all talk until the code runs.",
    "A good programmer looks both ways before crossing a one-way street.",
    "The goal of a programmer is to make things as simple as possible, as complex as necessary.",
    "If at first, you don’t succeed; call it version 1.0.",
    "When debugging, novices insert corrective code; experts remove defective code.",
    "The trouble with programmers is that you can never tell what a programmer is doing until it’s too late.",
    "Any code of your own that you haven’t looked at for six or more months might as well have been written by someone else.",
    "The best performance improvement is the transition from the nonworking state to the working state.",
    "Any fool can use a computer. Many do.",
    "I don’t care if it works on your machine! We are not shipping your machine!",
    "Why do we never have time to do it right, but always have time to do it over?",
    "A misplaced decimal point will always end up where it will do the greatest damage.",
    "The first 90% of the code accounts for the first 90% of the development time. The remaining 10% of the code accounts for the other 90% of the development time.",
    "It is easier to change the specification to fit the program than vice versa.",
    "The most important thing in the programming language is the name. A language will not succeed without a good name. I have recently invented a very good name and now I am looking for a suitable language.",
    "In C++ it’s harder to shoot yourself in the foot, but when you do, you blow off your whole leg.",
    "Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.",
    "Good design adds value faster than it adds cost.",
    "First learn computer science and all the theory. Next develop a programming style. Then forget all that and just hack.",
    "Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.",
    "To understand recursion, one must first understand recursion.",
    "The art of debugging is figuring out what you really told your program to do.",
    "The beginning of knowledge is the discovery of something we do not understand.",
    "One man’s constant is another man’s variable.",
    "You can’t have great software without a great team, and most software teams behave like dysfunctional families.",
    "One of my most productive days was throwing away 1,000 lines of code.",
    "The best way to predict the future is to invent it.",
    "Software undergoes beta testing shortly before it’s released. Beta is Latin for “still doesn’t work.”",
    "The most important single aspect of software development is to be clear about what you are trying to build.",
    "Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.",
    "The cheapest, fastest, and most reliable components are those that aren’t there.",
    "There are only two industries that refer to their customers as users.",
    "It’s not a bug, it’s an undocumented feature.",
    "Good code is its own best documentation. As you’re about to add a comment, ask yourself, “How can I improve the code so that this comment isn’t needed?”",
    "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it.",
    "The most important skill any programmer can learn is to write clear and understandable code.",
    "Code is like humor. When you have to explain it, it’s bad.",
    "The purpose of software engineering is to control complexity, not to create it.",
  ];
  
  export default quotes;
  