const quotes = [
  "Programming is the closest thing we have to magic.",
  "The best error message is the one that never shows up.",
  "If the code and the comments disagree, the comments are probably wrong.",
  "Expecto Patronum() - Defend your code against Dementor bugs.",
  "Winter is coming, bugs are coming - Brace your code!",
  "See my code. See my code! - Breaking Bug",
  "When in doubt, console.log('Hello World').",
  "I solemnly swear that my code is up to no good.",
  "You know nothing, bug-free Jon Snow.",
  "Hodor: the only one who understands asynchronous programming.",
  "The sorting hat says: 'You belong in the coding house.'",
  "You win or you debug. There is no middle ground.",
  "The night is dark and full of errors.",
  "Code is not a sprint, it's a marathon with infinite loops.",
  "I am the one who codes.",
  "I code and I know things. - Tyrion Lannister",
  "A Lannister always comments his code.",
  "I drink and I code things. - Tyrion Lannister",
  "The one where the code works perfectly.",
  "You either code like a hero or live long enough to see yourself become a debugger.",
  "I am the danger. I am the one who codes!",
  "It's not a bug; it's a feature with unexpected behavior.",
  "The best way to predict the future is to code it.",
  "The night is full of errors and typos.",
  "I am Groot. (Translated: I am a programmer.)",
  "I'd rather be coding.",
  "Code is power. - Game of Bugs",
  "May the source be with you.",
  "It's not about the language, it's about the logic.",
  "I find your lack of coding skills disturbing.",
  "Friends don't let friends write Java.",
  "When you play the game of code, you win or you learn.",
  "The best code is no code. - The Tao of Programming",
  "You can't refactor the past. - Harry Potter and the Git of Time",
  "I am not a coder; I am a code wizard.",
  "Code before dishonor.",
  "Code like nobody is watching.",
  "Code is like a dragon; tame it or it will burn you.",
  "The sorting hat has sorted you into the Debugging House.",
  "The wand chooses the coder. - Harry Potter and the Chamber of Debugging",
  "What do we say to the god of bugs? Not today.",
  "Yer a coder Harry! - Rubeus Hagrid - COO -Hogwarts PVT LTD",
  "The journey of a thousand bugs begins with a single line of code.",
];

export default quotes;
